# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy the package.json and install dependencies
COPY FrontEnd/package*.json /app/
RUN npm install

# Copy the rest of the application code
COPY FrontEnd/ /app/

# Build the app
RUN npm run build

# Use an official Nginx image to serve the app
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Run Nginx
CMD ["nginx", "-g", "daemon off;"]
